-- Initial installation in the independent OpoPlan project only.
-- Generated by npm run schema:bundle; do not apply again to an installed database.
begin;

-- 202610080001_model.sql
-- OpoPlan 001 · normalized private model. Apply only to the independent OpoPlan project.

create table public.profiles (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 display_name text not null default '', preferences jsonb not null,
 check(id=owner_id)
);
create table public.oppositions (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 name text not null check(length(trim(name)) between 1 and 200), exam_date date, archived boolean not null default false
);
create table public.nodes (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 opposition_id uuid not null,parent_id uuid,source_node_id uuid,name text not null check(length(trim(name)) between 1 and 300),kind text not null check(kind in ('container','block')),position integer not null default 0,archived boolean not null default false,importance integer not null default 3 check(importance between 1 and 5),estimated_minutes integer not null default 20 check(estimated_minutes between 1 and 1440),notes text not null default '',
 foreign key(owner_id,opposition_id) references public.oppositions(owner_id,id),
 foreign key(owner_id,parent_id) references public.nodes(owner_id,id) deferrable initially deferred,
 foreign key(owner_id,source_node_id) references public.nodes(owner_id,id) deferrable initially deferred,
 check(parent_id is distinct from id)
);
create table public.categories (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 name text not null check(length(trim(name)) between 1 and 200),color text not null default '#287462' 
);
create table public.plan_tasks (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 opposition_id uuid not null,node_id uuid,category_id uuid,name text not null check(length(trim(name)) between 1 and 300),kind text not null check(kind in ('study','review','practice')),scheduled_day date not null,original_day date not null,estimated_minutes integer not null check(estimated_minutes between 1 and 1440),status text not null check(status in ('pending','completed','cancelled')),notes text not null default '',completed_session_id uuid,
 foreign key(owner_id,opposition_id) references public.oppositions(owner_id,id),foreign key(owner_id,node_id) references public.nodes(owner_id,id),foreign key(owner_id,category_id) references public.categories(owner_id,id)
);
create table public.sessions (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 opposition_id uuid not null,kind text not null check(kind in ('study','review','practice')),started_at timestamptz not null,ended_at timestamptz not null,duration_seconds integer not null check(duration_seconds between 1 and 604800),notes text not null default '',concentration integer check(concentration between 1 and 5),difficulty integer check(difficulty between 1 and 5),source text not null check(source in ('manual','timer')),planned_task_id uuid,
 foreign key(owner_id,opposition_id) references public.oppositions(owner_id,id),foreign key(owner_id,planned_task_id) references public.plan_tasks(owner_id,id) deferrable initially deferred,check(ended_at>=started_at)
);
create table public.session_blocks (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 session_id uuid not null,node_id uuid not null,allocated_seconds integer not null check(allocated_seconds>=0),progress integer not null default 0 check(progress between 0 and 100),completed boolean not null default false,
 foreign key(owner_id,session_id) references public.sessions(owner_id,id) deferrable initially deferred,foreign key(owner_id,node_id) references public.nodes(owner_id,id),unique(owner_id,session_id,node_id),check(not completed or progress=100)
);
create table public.memory_events (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 node_id uuid not null,session_id uuid,kind text not null check(kind in ('study','review','reschedule','reset','exclude','include','correction','void')),occurred_at timestamptz not null,study_day date not null,timezone text not null,rating text check(rating in ('mal','regular','bien')),notes text not null default '',manual_due date,target_event_id uuid,rules jsonb not null,scheduled_due date,
 foreign key(owner_id,node_id) references public.nodes(owner_id,id),foreign key(owner_id,session_id) references public.sessions(owner_id,id) deferrable initially deferred,foreign key(owner_id,target_event_id) references public.memory_events(owner_id,id) deferrable initially deferred,
 check((kind in ('review','correction'))=(rating is not null)),check((kind in ('correction','void'))=(target_event_id is not null)),check((kind='reschedule')=(manual_due is not null)),check(kind not in ('study','review') or session_id is not null)
);
create table public.test_results (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 session_id uuid not null,category_id uuid,name text not null,test_type text not null,question_count integer not null check(question_count>0),correct integer not null check(correct>=0),wrong integer not null check(wrong>=0),blank integer not null check(blank>=0),penalty numeric not null check(penalty>=0),score numeric not null,max_score numeric not null check(max_score>0),score_manual boolean not null default false,notes text not null default '',
 foreign key(owner_id,session_id) references public.sessions(owner_id,id) deferrable initially deferred,foreign key(owner_id,category_id) references public.categories(owner_id,id),unique(owner_id,session_id),check(correct+wrong+blank=question_count)
);
create table public.test_links (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 test_id uuid not null,node_id uuid not null,error_notes text not null default '',foreign key(owner_id,test_id) references public.test_results(owner_id,id) deferrable initially deferred,foreign key(owner_id,node_id) references public.nodes(owner_id,id),unique(owner_id,test_id,node_id)
);
create table public.coverage_snapshots (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 opposition_id uuid not null,day date not null,active_blocks integer not null check(active_blocks>=0),coverage jsonb not null,foreign key(owner_id,opposition_id) references public.oppositions(owner_id,id)
);
create table public.push_subscriptions (
 id uuid not null default gen_random_uuid(),
 owner_id uuid not null references auth.users(id) on delete cascade,
 version integer not null default 1 check(version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 deleted_at timestamptz,
 primary key(owner_id,id),
 endpoint text not null,subscription jsonb not null,last_sent_day date,unique(owner_id,endpoint)
);
alter table public.plan_tasks add constraint completed_session_owner_fk foreign key(owner_id,completed_session_id) references public.sessions(owner_id,id) deferrable initially deferred;
create table public.review_state(owner_id uuid not null references auth.users(id) on delete cascade,node_id uuid not null,state jsonb not null,updated_at timestamptz not null default now(),primary key(owner_id,node_id),foreign key(owner_id,node_id) references public.nodes(owner_id,id));
create table public.sync_operations(owner_id uuid not null references auth.users(id) on delete cascade,id uuid not null,payload jsonb not null,result jsonb not null,before_rows jsonb not null,created_at timestamptz not null default now(),primary key(owner_id,id));
create index nodes_tree on public.nodes(owner_id,opposition_id,parent_id,position);
create index sessions_dates on public.sessions(owner_id,opposition_id,started_at);
create index memory_chronology on public.memory_events(owner_id,node_id,occurred_at,id);
create index tasks_dates on public.plan_tasks(owner_id,opposition_id,scheduled_day,status);
create index assignments_sessions on public.session_blocks(owner_id,session_id);
create index test_categories on public.test_results(owner_id,category_id);
alter table public.profiles enable row level security;
create policy owner_read on public.profiles for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.profiles for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.profiles for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.profiles for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.profiles from anon,authenticated;
grant select on public.profiles to authenticated;
alter table public.oppositions enable row level security;
create policy owner_read on public.oppositions for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.oppositions for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.oppositions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.oppositions for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.oppositions from anon,authenticated;
grant select on public.oppositions to authenticated;
alter table public.nodes enable row level security;
create policy owner_read on public.nodes for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.nodes for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.nodes for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.nodes for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.nodes from anon,authenticated;
grant select on public.nodes to authenticated;
alter table public.categories enable row level security;
create policy owner_read on public.categories for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.categories for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.categories for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.categories for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.categories from anon,authenticated;
grant select on public.categories to authenticated;
alter table public.plan_tasks enable row level security;
create policy owner_read on public.plan_tasks for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.plan_tasks for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.plan_tasks for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.plan_tasks for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.plan_tasks from anon,authenticated;
grant select on public.plan_tasks to authenticated;
alter table public.sessions enable row level security;
create policy owner_read on public.sessions for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.sessions for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.sessions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.sessions for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.sessions from anon,authenticated;
grant select on public.sessions to authenticated;
alter table public.session_blocks enable row level security;
create policy owner_read on public.session_blocks for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.session_blocks for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.session_blocks for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.session_blocks for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.session_blocks from anon,authenticated;
grant select on public.session_blocks to authenticated;
alter table public.memory_events enable row level security;
create policy owner_read on public.memory_events for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.memory_events for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.memory_events for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.memory_events for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.memory_events from anon,authenticated;
grant select on public.memory_events to authenticated;
alter table public.test_results enable row level security;
create policy owner_read on public.test_results for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.test_results for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.test_results for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.test_results for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.test_results from anon,authenticated;
grant select on public.test_results to authenticated;
alter table public.test_links enable row level security;
create policy owner_read on public.test_links for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.test_links for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.test_links for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.test_links for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.test_links from anon,authenticated;
grant select on public.test_links to authenticated;
alter table public.coverage_snapshots enable row level security;
create policy owner_read on public.coverage_snapshots for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.coverage_snapshots for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.coverage_snapshots for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.coverage_snapshots for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.coverage_snapshots from anon,authenticated;
grant select on public.coverage_snapshots to authenticated;
alter table public.push_subscriptions enable row level security;
create policy owner_read on public.push_subscriptions for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.push_subscriptions for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.push_subscriptions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.push_subscriptions for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.push_subscriptions from anon,authenticated;
grant select on public.push_subscriptions to authenticated;
alter table public.review_state enable row level security;
create policy owner_read on public.review_state for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.review_state for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.review_state for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.review_state for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.review_state from anon,authenticated;
grant select on public.review_state to authenticated;
alter table public.sync_operations enable row level security;
create policy owner_read on public.sync_operations for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert on public.sync_operations for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update on public.sync_operations for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_delete on public.sync_operations for delete to authenticated using ((select auth.uid())=owner_id);
revoke all on public.sync_operations from anon,authenticated;
grant select on public.sync_operations to authenticated;
-- All browser writes use the version-checked RPC; direct table mutation is intentionally revoked.


-- 202610080002_integrity.sql

create function public.validate_node() returns trigger language plpgsql set search_path='' as $$
declare p public.nodes; cycle_found boolean;
begin
 if new.parent_id is not null then
  select * into p from public.nodes where owner_id=new.owner_id and id=new.parent_id;
  if p.id is not null and (p.kind<>'container' or p.opposition_id<>new.opposition_id) then raise exception 'El padre debe ser un contenedor de la misma oposición'; end if;
  with recursive ancestors as (
   select id,parent_id,array[id] path from public.nodes where owner_id=new.owner_id and id=new.parent_id
   union all select n.id,n.parent_id,a.path||n.id from public.nodes n join ancestors a on n.id=a.parent_id and n.owner_id=new.owner_id where not n.id=any(a.path)
  ) select exists(select 1 from ancestors where id=new.id) into cycle_found;
  if cycle_found then raise exception 'No se permiten ciclos en el temario';end if;
 end if;
 if new.kind='block' and exists(select 1 from public.nodes where owner_id=new.owner_id and parent_id=new.id) then raise exception 'Un bloque revisable no puede contener hijos';end if;
 if tg_op='UPDATE' and new.opposition_id<>old.opposition_id then raise exception 'No se puede cambiar un nodo de oposición';end if;
 return new;
end $$;
create constraint trigger node_integrity after insert or update on public.nodes deferrable initially deferred for each row execute function public.validate_node();

create function public.validate_activity() returns trigger language plpgsql set search_path='' as $$
declare sid uuid; uid uuid; s public.sessions; sum_seconds bigint; count_blocks bigint; target public.memory_events;
begin
 uid=new.owner_id;
 if tg_table_name='sessions' then sid=new.id;else sid=new.session_id;end if;
 if tg_table_name='memory_events' then
  if (new.occurred_at at time zone new.timezone)::date<>new.study_day then raise exception 'El día no coincide con la zona horaria';end if;
  if (new.rules->>'version')::int<>1 or (new.rules->>'firstDays')::int not between 1 and 30 or (new.rules->>'secondDays')::int not between 1 and 60 or (new.rules->>'maxDays')::int not between 1 and 3650 or (new.rules->>'regularMultiplier')::numeric not between 1 and 2 then raise exception 'Reglas de repaso no válidas';end if;
  if new.target_event_id is not null then
   select * into target from public.memory_events where owner_id=uid and id=new.target_event_id;
   if target.node_id is distinct from new.node_id or target.kind not in ('study','review','reschedule','reset','include','exclude') or (new.kind='correction' and target.kind<>'review') then raise exception 'Corrección de evento no válida';end if;
  end if;
  if new.kind in ('study','review') and not exists(select 1 from public.session_blocks where owner_id=uid and session_id=sid and node_id=new.node_id and deleted_at is null and (new.kind='review' or completed)) then raise exception 'El evento debe pertenecer a un bloque registrado en la sesión';end if;
 end if;
 if sid is null then return new;end if;
 select * into s from public.sessions where owner_id=uid and id=sid;
 if s.id is null or s.deleted_at is not null then return new;end if;
 select coalesce(sum(allocated_seconds),0),count(*) into sum_seconds,count_blocks from public.session_blocks where owner_id=uid and session_id=sid and deleted_at is null;
 if (s.kind in ('study','review') and count_blocks=0) or (count_blocks>0 and sum_seconds<>s.duration_seconds) then raise exception 'El reparto de tiempo debe sumar exactamente la duración de la sesión';end if;
 if exists(select 1 from public.session_blocks a join public.nodes n on n.owner_id=a.owner_id and n.id=a.node_id where a.owner_id=uid and a.session_id=sid and a.deleted_at is null and (n.opposition_id<>s.opposition_id or n.kind<>'block')) then raise exception 'Bloque de sesión no válido';end if;
 if tg_table_name='memory_events' then
  if new.kind in ('study','review') and s.kind<>(case when new.kind='study' then 'study' else 'review' end) then raise exception 'Tipo de evento incompatible con sesión';end if;
 end if;
 if tg_table_name='test_results' and s.kind<>'practice' then raise exception 'Un test debe pertenecer a una sesión de práctica';end if;
 return new;
end $$;
create constraint trigger validate_sessions after insert or update on public.sessions deferrable initially deferred for each row execute function public.validate_activity();
create constraint trigger validate_session_blocks after insert or update on public.session_blocks deferrable initially deferred for each row execute function public.validate_activity();
create constraint trigger validate_memory_events after insert on public.memory_events deferrable initially deferred for each row execute function public.validate_activity();
create constraint trigger validate_tests after insert or update on public.test_results deferrable initially deferred for each row execute function public.validate_activity();


-- 202610080003_memory.sql

-- Same deterministic reducer as src/core/memory.ts. Dates use date arithmetic, never 24-hour milliseconds.
create function public.rebuild_memory(uid uuid,nid uuid) returns void language plpgsql security definer set search_path='' as $$
declare e record; studied boolean=false; reviews int=0; passes int=0; repetitions int=0; ease numeric=2.5; interval_days int=0; due date; automatic_due date; manual boolean=false; enabled boolean=true; rating text; last_day date; reason text='Completa el estudio inicial para programar el primer repaso.'; difficulties int=0; q int; first_days int; second_days int; max_days int; multiplier numeric;
begin
 for e in
  with mods as (select distinct on(target_event_id) * from public.memory_events where owner_id=uid and node_id=nid and deleted_at is null and kind in ('correction','void') order by target_event_id,occurred_at desc,id desc),
  effective as (select ev.*,coalesce(m.rating,ev.rating) effective_rating,coalesce(m.notes,ev.notes) effective_notes from public.memory_events ev left join mods m on m.target_event_id=ev.id where ev.owner_id=uid and ev.node_id=nid and ev.deleted_at is null and ev.kind not in ('correction','void') and coalesce(m.kind,'')<>'void'),
  selected as (select *,row_number() over(partition by study_day,kind order by occurred_at desc,id desc) day_rank from effective)
  select * from selected where kind<>'review' or day_rank=1 order by occurred_at,id
 loop
  first_days=(e.rules->>'firstDays')::int;second_days=(e.rules->>'secondDays')::int;max_days=(e.rules->>'maxDays')::int;multiplier=(e.rules->>'regularMultiplier')::numeric;
  if e.kind='study' and not studied then studied=true;passes=1+reviews;last_day=e.study_day;interval_days=first_days;due=e.study_day+first_days;automatic_due=due;manual=false;reason='Estudio inicial completado · primer repaso en '||first_days||' día(s).';
  elsif e.kind='review' then
   rating=e.effective_rating;q=case rating when 'mal' then 1 when 'regular' then 3 else 5 end;
   ease=greatest(1.3,round(ease+0.1-(5-q)*(0.08+(5-q)*0.02),2));
   if q<3 then repetitions=0;interval_days=first_days;difficulties=difficulties+1;
   else repetitions=repetitions+1;
    if rating='regular' then interval_days=greatest(first_days,round(greatest(1,interval_days)*multiplier)::int);
    elsif repetitions=1 then interval_days=first_days;
    elsif repetitions=2 then interval_days=second_days;
    else interval_days=round(interval_days*ease)::int;end if;
   end if;
   interval_days=least(max_days,greatest(1,interval_days));reviews=reviews+1;passes=case when studied then 1+reviews else 0 end;last_day=e.study_day;due=e.study_day+interval_days;automatic_due=due;manual=false;reason=upper(rating)||' (SM-2: '||q||'/5) · intervalo '||interval_days||' día(s) · facilidad '||ease||'.';
  elsif e.kind='reschedule' then due=e.manual_due;manual=true;reason='Fecha elegida manualmente: '||e.effective_notes||'. Fecha automática: '||coalesce(automatic_due::text,'sin programar')||'.';
  elsif e.kind='reset' then repetitions=0;ease=2.5;interval_days=0;rating=null;last_day=null;manual=false;due=case when studied then e.study_day+first_days else null end;automatic_due=due;reason='Programación reiniciada. Historial y pasadas conservados.';
  elsif e.kind='exclude' then enabled=false;reason='Excluido de repetición espaciada.';
  elsif e.kind='include' then enabled=true;reason='Repetición espaciada activada.';end if;
 end loop;
 insert into public.review_state(owner_id,node_id,state,updated_at) values(uid,nid,jsonb_build_object('studied',studied,'passes',passes,'reviews',reviews,'repetitions',repetitions,'ease',ease,'interval',interval_days,'due',due,'automaticDue',automatic_due,'manual',manual,'enabled',enabled,'rating',rating,'lastDay',last_day,'reason',reason,'difficulties',difficulties),now()) on conflict(owner_id,node_id) do update set state=excluded.state,updated_at=excluded.updated_at;
end $$;
revoke all on function public.rebuild_memory(uuid,uuid) from public,anon,authenticated;
create function public.memory_changed() returns trigger language plpgsql security definer set search_path='' as $$begin perform public.rebuild_memory(new.owner_id,new.node_id);return new;end $$;
create constraint trigger memory_replay after insert on public.memory_events deferrable initially deferred for each row execute function public.memory_changed();


-- 202610080004_sync.sql

create function public.apply_operations(operation_id uuid,changes jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid=auth.uid();item jsonb;rowdata jsonb;remote jsonb;current_version integer;tbl text;rid uuid;expected integer;conflicts jsonb='[]';result jsonb;previous jsonb='[]';columns text;updates text;existing jsonb;
begin
 if uid is null then raise exception 'Debes iniciar sesión' using errcode='28000';end if;
 if jsonb_typeof(changes)<>'array' or jsonb_array_length(changes) not between 1 and 50000 then raise exception 'Lote de cambios no válido';end if;
 perform pg_advisory_xact_lock(hashtextextended(uid::text,0));
 select op.payload,op.result into existing,result from public.sync_operations op where op.owner_id=uid and op.id=operation_id;
 if found then if existing<>changes then raise exception 'Un identificador de operación no se puede reutilizar con otro contenido';end if;return result;end if;
 if exists(select 1 from jsonb_array_elements(changes) x group by x->>'table',x->'row'->>'id' having count(*)>1) then raise exception 'Fila duplicada dentro del lote';end if;
 for item in select * from jsonb_array_elements(changes) loop
  tbl=item->>'table';rid=(item->'row'->>'id')::uuid;expected=(item->>'expected_version')::int;
  if tbl not in ('profiles','oppositions','nodes','categories','sessions','session_blocks','memory_events','plan_tasks','test_results','test_links','coverage_snapshots','push_subscriptions') then raise exception 'Tabla no permitida';end if;
  if item->'row'->>'owner_id' is distinct from uid::text or rid is null or expected<0 then raise exception 'Propietario o versión no válidos';end if;
  execute format('select to_jsonb(t) from public.%I t where owner_id=$1 and id=$2',tbl) into remote using uid,rid;
  current_version=coalesce((remote->>'version')::int,0);
  if current_version<>expected then conflicts=conflicts||jsonb_build_array(jsonb_build_object('table',tbl,'id',rid,'expected',expected,'actual',current_version,'remote',remote));end if;
  if tbl='memory_events' and current_version>0 then raise exception 'El historial es inmutable. Añade una corrección o anulación.';end if;
  previous=previous||jsonb_build_array(jsonb_build_object('table',tbl,'id',rid,'row',remote));
 end loop;
 if jsonb_array_length(conflicts)>0 then return jsonb_build_object('conflicts',conflicts);end if;
 for item in select * from jsonb_array_elements(changes) loop
  tbl=item->>'table';rid=(item->'row'->>'id')::uuid;expected=(item->>'expected_version')::int;
  select string_agg(format('%I',attname),',' order by attnum),string_agg(format('%I=excluded.%I',attname,attname),',' order by attnum) filter(where attname not in ('id','owner_id','created_at')) into columns,updates from pg_attribute where attrelid=('public.'||tbl)::regclass and attnum>0 and not attisdropped;
  select x->'row' into remote from jsonb_array_elements(previous) x where x->>'table'=tbl and x->>'id'=rid::text;
  rowdata=(item->'row')||jsonb_build_object('owner_id',uid,'version',expected+1,'updated_at',now(),'created_at',coalesce(remote->'created_at',to_jsonb(now())));
  execute format('insert into public.%1$I(%2$s) select %2$s from jsonb_populate_record(null::public.%1$I,$1) on conflict(owner_id,id) do update set %3$s',tbl,columns,updates) using rowdata;
 end loop;
 -- Immediate constraint evaluation ensures no false cloud-saved response.
 set constraints all immediate;
 result=jsonb_build_object('ok',true,'operation_id',operation_id);
 insert into public.sync_operations(owner_id,id,payload,result,before_rows) values(uid,operation_id,changes,result,previous);
 return result;
end $$;
revoke all on function public.apply_operations(uuid,jsonb) from public,anon;
grant execute on function public.apply_operations(uuid,jsonb) to authenticated;
-- Tombstones are UPDATEs, so Realtime can apply RLS to them.
do $$declare t text;begin
 if exists(select 1 from pg_publication where pubname='supabase_realtime') then
  foreach t in array array['profiles','oppositions','nodes','categories','sessions','session_blocks','memory_events','plan_tasks','test_results','test_links','coverage_snapshots'] loop
   if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then execute format('alter publication supabase_realtime add table public.%I',t);end if;
  end loop;
 end if;
end $$;


-- 202610080005_validation.sql

create function public.valid_memory_rules(p jsonb) returns boolean language sql immutable set search_path='' as $$
 select coalesce(jsonb_typeof(p)='object'
  and p ?& array['version','firstDays','secondDays','maxDays','regularMultiplier']
  and jsonb_typeof(p->'version')='number' and jsonb_typeof(p->'firstDays')='number' and jsonb_typeof(p->'secondDays')='number' and jsonb_typeof(p->'maxDays')='number' and jsonb_typeof(p->'regularMultiplier')='number'
  and (p->>'version')::numeric=1
  and (p->>'firstDays')::numeric between 1 and 30
  and (p->>'firstDays')::numeric=trunc((p->>'firstDays')::numeric)
  and (p->>'secondDays')::numeric between 1 and 60
  and (p->>'secondDays')::numeric=trunc((p->>'secondDays')::numeric)
  and (p->>'maxDays')::numeric between greatest((p->>'firstDays')::numeric,(p->>'secondDays')::numeric) and 3650
  and (p->>'maxDays')::numeric=trunc((p->>'maxDays')::numeric)
  and (p->>'regularMultiplier')::numeric between 1 and 2,false)
$$;
alter table public.memory_events add constraint complete_memory_rules check(public.valid_memory_rules(rules));
create function public.validate_profile() returns trigger language plpgsql set search_path='' as $$
declare p jsonb=new.preferences;field text;limit_value integer;day jsonb;
begin
 if jsonb_typeof(p)<>'object' or not p ?& array['timezone','theme','dailyMinutes','weeklyMinutes','reviewMinutes','studyDays','pomodoroWork','pomodoroBreak','reminders','reminderHour','language','rules'] then raise exception 'Configuración incompleta';end if;
 if jsonb_typeof(p->'timezone')<>'string' or jsonb_typeof(p->'theme')<>'string' or jsonb_typeof(p->'language')<>'string' or not exists(select 1 from pg_timezone_names where name=p->>'timezone') or p->>'theme' not in ('light','dark','auto') or p->>'language'<>'es' or jsonb_typeof(p->'reminders')<>'boolean' or not public.valid_memory_rules(p->'rules') then raise exception 'Configuración no válida';end if;
 foreach field in array array['dailyMinutes','weeklyMinutes','reviewMinutes','pomodoroWork','pomodoroBreak','reminderHour'] loop
  limit_value=case field when 'weeklyMinutes' then 10080 when 'pomodoroWork' then 180 when 'pomodoroBreak' then 60 when 'reminderHour' then 23 else 1440 end;
  if jsonb_typeof(p->field)<>'number' or (p->>field)::numeric<>trunc((p->>field)::numeric) or (p->>field)::numeric not between (case when field in ('pomodoroWork','pomodoroBreak') then 1 else 0 end) and limit_value then raise exception 'Objetivo o intervalo no válido';end if;
 end loop;
 if jsonb_typeof(p->'studyDays')<>'array' then raise exception 'Días de estudio no válidos';end if;
 for day in select * from jsonb_array_elements(p->'studyDays') loop
  if jsonb_typeof(day)<>'number' or day::text::numeric not between 0 and 6 or day::text::numeric<>trunc(day::text::numeric) then raise exception 'Día de estudio no válido';end if;
 end loop;
 return new;
end $$;
create trigger profile_configuration before insert or update on public.profiles for each row execute function public.validate_profile();

create function public.validate_links() returns trigger language plpgsql set search_path='' as $$
declare n public.nodes;s public.sessions;t public.test_results;opid uuid;
begin
 if tg_table_name='test_links' then
  select * into t from public.test_results where owner_id=new.owner_id and id=new.test_id;
  select * into s from public.sessions where owner_id=new.owner_id and id=t.session_id;
  opid=s.opposition_id;
 else
  opid=new.opposition_id;
  if (new.status='completed')<>(new.completed_session_id is not null) then raise exception 'Actividad completada sin sesión real';end if;
  if new.completed_session_id is not null then
   select * into s from public.sessions where owner_id=new.owner_id and id=new.completed_session_id;
   if s.opposition_id<>new.opposition_id or s.kind<>new.kind then raise exception 'Sesión incompatible con actividad prevista';end if;
  end if;
 end if;
 if new.node_id is not null then
  select * into n from public.nodes where owner_id=new.owner_id and id=new.node_id;
  if n.kind<>'block' or n.opposition_id<>opid then raise exception 'Bloque incompatible con actividad';end if;
 end if;
 return new;
end $$;
create constraint trigger test_link_integrity after insert or update on public.test_links deferrable initially deferred for each row execute function public.validate_links();
create constraint trigger plan_link_integrity after insert or update on public.plan_tasks deferrable initially deferred for each row execute function public.validate_links();
revoke all on function public.valid_memory_rules(jsonb),public.validate_profile(),public.validate_links() from public,anon,authenticated;

commit;
